# Generated by Django 5.2.1 on 2025-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommending_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="orders", to="recommending_system.product"
                    ),
                ),
            ],
        ),
    ]
